package pl.cba.radeckiuczony.mushroomer;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.support.v7.app.AppCompatActivity;

import static pl.cba.radeckiuczony.mushroomer.SQLHelper.TABLE_QUESTION;

public class Queries {
    public static String QUERY_POCH_BLASZ_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'iglasty'";
    public static String QUERY_PIERS_BLASZ_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'iglasty'";
    public static String QUERY_NIC_BLASZ_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'iglasty'";
    public static String QUERY_DWA_BLASZ_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'iglasty'";

    public static String QUERY_POCH_POR_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'pory' AND LAS LIKE 'iglasty'";
    public static String QUERY_PIERS_POR_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'pory' AND LAS LIKE 'iglasty'";
    public static String QUERY_NIC_POR_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'pory' AND LAS LIKE 'iglasty'";
    public static String QUERY_DWA_POR_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'pory' AND LAS LIKE 'iglasty'";

    public static String QUERY_POCH_NIC_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'nic' AND LAS LIKE 'iglasty'";
    public static String QUERY_PIERS_NIC_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'nic' AND LAS LIKE 'iglasty'";
    public static String QUERY_NIC_NIC_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'nic' AND LAS LIKE 'iglasty'";
    public static String QUERY_DWA_NIC_IG = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'nic' AND LAS LIKE 'iglasty'";



    public static String QUERY_POCH_BLASZ_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'lisc'";
    public static String QUERY_PIERS_BLASZ_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'lisc'";
    public static String QUERY_NIC_BLASZ_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'lisc'";
    public static String QUERY_DWA_BLASZ_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'lisc'";

    public static String QUERY_POCH_POR_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'pory' AND LAS LIKE 'lisc'";
    public static String QUERY_PIERS_POR_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'pory' AND LAS LIKE 'lisc'";
    public static String QUERY_NIC_POR_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'pory' AND LAS LIKE 'lisc'";
    public static String QUERY_DWA_POR_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'pory' AND LAS LIKE 'lisc'";

    public static String QUERY_POCH_NIC_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'nic' AND LAS LIKE 'lisc'";
    public static String QUERY_PIERS_NIC_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'nic' AND LAS LIKE 'lisc'";
    public static String QUERY_NIC_NIC_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'nic' AND LAS LIKE 'lisc'";
    public static String QUERY_DWA_NIC_LISC = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'nic' AND LAS LIKE 'lisc'";



    public static String QUERY_POCH_BLASZ_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'mieszany'";
    public static String QUERY_PIERS_BLASZ_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'mieszany'";
    public static String QUERY_NIC_BLASZ_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'mieszany'";
    public static String QUERY_DWA_BLASZ_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'mieszany'";

    public static String QUERY_POCH_POR_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'pory' AND LAS LIKE 'mieszany'";
    public static String QUERY_PIERS_POR_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'pory' AND LAS LIKE 'mieszany'";
    public static String QUERY_NIC_POR_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'pory' AND LAS LIKE 'mieszany'";
    public static String QUERY_DWA_POR_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'pory' AND LAS LIKE 'mieszany'";

    public static String QUERY_POCH_NIC_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'nic' AND LAS LIKE 'mieszany'";
    public static String QUERY_PIERS_NIC_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'nic' AND LAS LIKE 'mieszany'";
    public static String QUERY_NIC_NIC_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'nic' AND LAS LIKE 'mieszany'";
    public static String QUERY_DWA_NIC_MIESZANY = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'nic' AND LAS LIKE 'mieszany'";



    public static String QUERY_POCH_BLASZ_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'laka'";
    public static String QUERY_PIERS_BLASZ_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'laka'";
    public static String QUERY_NIC_BLASZ_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'laka'";
    public static String QUERY_DWA_BLASZ_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'blaszki' AND LAS LIKE 'laka'";

    public static String QUERY_POCH_POR_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'pory' AND LAS LIKE 'laka'";
    public static String QUERY_PIERS_POR_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'pory' AND LAS LIKE 'laka'";
    public static String QUERY_NIC_POR_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'pory' AND LAS LIKE 'laka'";
    public static String QUERY_DWA_POR_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'pory' AND LAS LIKE 'laka'";

    public static String QUERY_POCH_NIC_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'poch' AND BLASZKI LIKE 'nic' AND LAS LIKE 'laka'";
    public static String QUERY_PIERS_NIC_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'piers' AND BLASZKI LIKE 'nic' AND LAS LIKE 'laka'";
    public static String QUERY_NIC_NIC_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'nic' AND BLASZKI LIKE 'nic' AND LAS LIKE 'laka'";
    public static String QUERY_DWA_NIC_LAKA = "SELECT * FROM TABLE WHERE KSZTALT LIKE  %s AND POCHPIERS LIKE 'dwa' AND BLASZKI LIKE 'nic' AND LAS LIKE 'laka'";

}